### ISSUE TITLE
Where is Resource: !Ref 'logs/log-group' and Resource: !Ref 'logs/log-stream' defined

### ISSUE THREAD

**Issue by markelrod** [aws-quickstart/quickstart-compliance-common#46]
Both vpc-management.template and vpc-production.template have policy section that references undefined resources. Are they supposed to be defined in logging.template?

```
Policies:
      - PolicyName: cloudwatchlogsrole
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
            Effect: Allow
            Resource: '*'
          - Effect: Allow
            Action:
              - logs:PutLogEvents
            Resource: !Ref 'logs/log-stream'
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
            Resource: !Ref 'logs/log-group'
```
